<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import BaseModal from './BaseModal.vue'
import { adminFetch, type AdminAuth } from './api'
const props = defineProps<{ organizationId: string; auth: AdminAuth }>()
type ChannelType = 'DISCORD_WEBHOOK' | 'TELEGRAM_BOT'; type Channel = { id: string; organizationId: string; type: ChannelType; enabled: boolean }
const channels = ref<Channel[]>([]); const busy = ref(false); const message = ref(''); const modalOpen = ref(false); const form = ref({ type: 'DISCORD_WEBHOOK' as ChannelType, target: '', secret: '' })
async function load() { if (!props.organizationId) return; busy.value = true; try { channels.value = await adminFetch<Channel[]>(`/api/admin/organizations/${props.organizationId}/notification-channels`, props.auth) } catch (error) { message.value = error instanceof Error ? error.message : '채널 조회 실패' } finally { busy.value = false } }
async function create() { busy.value = true; try { await adminFetch(`/api/admin/organizations/${props.organizationId}/notification-channels`, props.auth, { method: 'POST', body: JSON.stringify({ type: form.value.type, target: form.value.target, secret: form.value.secret || null }) }); form.value.target = ''; form.value.secret = ''; modalOpen.value = false; message.value = '알림 채널을 암호화하여 등록했습니다.'; await load() } catch (error) { message.value = error instanceof Error ? error.message : '채널 등록 실패' } finally { busy.value = false } }
async function toggle(channel: Channel) { const updated = await adminFetch<Channel>(`/api/admin/organizations/${props.organizationId}/notification-channels/${channel.id}`, props.auth, { method: 'PATCH', body: JSON.stringify({ enabled: !channel.enabled }) }); Object.assign(channel, updated); message.value = `${channel.type} 채널을 ${channel.enabled ? '활성화' : '비활성화'}했습니다.` }
watch(() => props.organizationId, load); onMounted(load)
</script>
<template><section class="page-stack"><div class="page-hero"><div><p class="eyebrow">ALERT CHANNELS</p><h1>알림 설정</h1><p>Endpoint 장애와 복구 이벤트를 Discord 또는 Telegram으로 전달합니다.</p></div><button class="primary-button" :disabled="!organizationId" @click="modalOpen = true">＋ 채널 등록</button></div><p v-if="message" class="inline-alert">{{ message }}</p><div v-if="channels.length" class="channel-grid"><article v-for="channel in channels" :key="channel.id" class="surface-card channel-card"><div class="channel-logo" :class="channel.type === 'DISCORD_WEBHOOK' ? 'discord' : 'telegram'">{{ channel.type === 'DISCORD_WEBHOOK' ? 'D' : 'T' }}</div><div><span class="card-kicker">{{ channel.type === 'DISCORD_WEBHOOK' ? 'DISCORD' : 'TELEGRAM' }}</span><h2>{{ channel.type === 'DISCORD_WEBHOOK' ? 'Webhook Channel' : 'Bot Channel' }}</h2><p>대상과 자격증명은 AES-GCM으로 암호화되어 저장됩니다.</p></div><label class="switch"><input :checked="channel.enabled" type="checkbox" @change="toggle(channel)" /><span></span></label><div class="channel-state"><span class="status-chip tiny" :class="channel.enabled ? 'healthy' : 'unknown'">{{ channel.enabled ? 'ENABLED' : 'PAUSED' }}</span><small class="mono">{{ channel.id }}</small></div></article></div><div v-else class="surface-card empty-state"><span>◉</span><h3>알림 채널이 없습니다</h3><p>첫 채널을 등록해 장애를 놓치지 마세요.</p><button class="text-button" @click="modalOpen = true">알림 채널 등록</button></div><BaseModal :open="modalOpen" title="알림 채널 등록" description="민감한 URL과 토큰은 암호화되어 저장됩니다." @close="modalOpen = false"><div class="modal-form"><label class="field">채널 유형<select v-model="form.type"><option value="DISCORD_WEBHOOK">Discord Webhook</option><option value="TELEGRAM_BOT">Telegram Bot</option></select></label><label class="field">{{ form.type === 'DISCORD_WEBHOOK' ? 'Webhook URL' : 'Chat ID' }}<input v-model.trim="form.target" :placeholder="form.type === 'DISCORD_WEBHOOK' ? 'https://discord.com/api/webhooks/…' : '-1001234567890'" /></label><label v-if="form.type === 'TELEGRAM_BOT'" class="field">Bot Token<input v-model="form.secret" type="password" autocomplete="off" placeholder="123456:bot-token" /></label></div><template #footer><button class="secondary-button" @click="modalOpen = false">취소</button><button class="primary-button" :disabled="busy || !form.target || (form.type === 'TELEGRAM_BOT' && !form.secret)" @click="create">채널 등록</button></template></BaseModal></section></template>
