<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import BaseModal from './BaseModal.vue'
import { adminFetch, type AdminAuth } from './api'

const props = defineProps<{ organizationId: string; auth: AdminAuth; platformAdmin: boolean }>()
const emit = defineEmits<{ organizationsChanged: []; organizationSelected: [id: string] }>()
type Project = { id: string; organizationId: string; teamId?: string | null; name: string; status: string }
type Team = { id: string; name: string; status: string }
type Service = { id: string; serviceKey: string; displayName: string; enabled: boolean }
type ApiKey = { id: string; name: string; keyPrefix: string; status: string; expiresAt?: string; lastUsedAt?: string; createdAt: string }
type Quota = { projectId: string; requestsPerMinute: number; monthlyTokenLimit: number | null }
type ContentPolicy = { projectId: string; mode: 'METADATA_ONLY' | 'FULL_ENCRYPTED'; retentionDays: number | null }
type AlertPolicy = { projectId: string; requestsPerMinuteThreshold: number | null; errorRatePercentThreshold: number | null; monthlyTokenUsagePercentThreshold: number | null; cooldownSeconds: number }
const projects = ref<Project[]>([]); const teams = ref<Team[]>([]); const services = ref<Service[]>([]); const keys = ref<ApiKey[]>([])
const selectedId = ref(sessionStorage.getItem('aiconnect.setup.projectId') ?? ''); const selected = computed(() => projects.value.find(item => item.id === selectedId.value))
const quota = ref<Quota | null>(null); const retention = ref<ContentPolicy | null>(null); const alert = ref<AlertPolicy | null>(null)
const busy = ref(false); const message = ref(''); const projectOpen = ref(false); const orgOpen = ref(false); const keyOpen = ref(false); const serviceOpen = ref(false); const policyOpen = ref(false); const secretOpen = ref(false)
const projectName = ref(''); const projectTeamId = ref(''); const orgName = ref(''); const keyName = ref(''); const expiresAt = ref(''); const serviceId = ref(''); const issuedSecret = ref('')
const form = ref({ requestsPerMinute: 60, monthlyTokenLimit: null as number | null, mode: 'METADATA_ONLY' as ContentPolicy['mode'], retentionDays: 30, requestsPerMinuteThreshold: null as number | null, errorRatePercentThreshold: null as number | null, monthlyTokenUsagePercentThreshold: null as number | null, cooldownSeconds: 900 })
async function load() {
  if (!props.organizationId) { projects.value = []; keys.value = []; return }
  busy.value = true
  try {
    const [projectItems, teamItems, serviceItems] = await Promise.all([adminFetch<Project[]>(`/api/admin/organizations/${props.organizationId}/projects`, props.auth), adminFetch<Team[]>(`/api/admin/organizations/${props.organizationId}/teams`, props.auth), adminFetch<Service[]>(`/api/admin/organizations/${props.organizationId}/services`, props.auth)])
    projects.value = projectItems; teams.value = teamItems; services.value = serviceItems
    if (!projects.value.some(item => item.id === selectedId.value)) selectedId.value = projects.value[0]?.id ?? ''
    if (selectedId.value) await selectProject(selectedId.value)
  } catch (error) { message.value = error instanceof Error ? error.message : '프로젝트 정보를 불러오지 못했습니다.' }
  finally { busy.value = false }
}
async function selectProject(id: string) {
  selectedId.value = id; sessionStorage.setItem('aiconnect.setup.projectId', id)
  const [keyItems, quotaValue, retentionValue, alertValue] = await Promise.all([adminFetch<ApiKey[]>(`/api/admin/projects/${id}/api-keys`, props.auth), adminFetch<Quota>(`/api/admin/projects/${id}/quota`, props.auth), adminFetch<ContentPolicy>(`/api/admin/projects/${id}/content-policy`, props.auth), adminFetch<AlertPolicy>(`/api/admin/projects/${id}/alert-policy`, props.auth)])
  keys.value = keyItems; quota.value = quotaValue; retention.value = retentionValue; alert.value = alertValue
}
async function createOrganization() { busy.value = true; try { const value = await adminFetch<{ id: string }>('/api/admin/organizations', props.auth, { method: 'POST', body: JSON.stringify({ name: orgName.value }) }); orgOpen.value = false; orgName.value = ''; emit('organizationsChanged'); emit('organizationSelected', value.id) } catch (error) { message.value = error instanceof Error ? error.message : '조직 생성 실패' } finally { busy.value = false } }
async function createProject() { busy.value = true; try { const value = await adminFetch<Project>('/api/admin/projects', props.auth, { method: 'POST', body: JSON.stringify({ organizationId: props.organizationId, teamId: projectTeamId.value || null, name: projectName.value }) }); projectOpen.value = false; projectName.value = ''; projectTeamId.value = ''; await load(); await selectProject(value.id); message.value = '팀 소유 프로젝트가 생성되었습니다.' } catch (error) { message.value = error instanceof Error ? error.message : '프로젝트 생성 실패' } finally { busy.value = false } }
async function issueKey() { if (!selectedId.value) return; busy.value = true; try { const value = await adminFetch<{ secret: string }>(`/api/admin/projects/${selectedId.value}/api-keys`, props.auth, { method: 'POST', body: JSON.stringify({ name: keyName.value, expiresAt: expiresAt.value ? new Date(expiresAt.value).toISOString() : null }) }); issuedSecret.value = value.secret; keyName.value = ''; expiresAt.value = ''; keyOpen.value = false; secretOpen.value = true; await selectProject(selectedId.value) } catch (error) { message.value = error instanceof Error ? error.message : '키 발급 실패' } finally { busy.value = false } }
async function grantService() { if (!selectedId.value || !serviceId.value) return; busy.value = true; try { await adminFetch(`/api/admin/projects/${selectedId.value}/service-access`, props.auth, { method: 'POST', body: JSON.stringify({ serviceId: serviceId.value }) }); serviceOpen.value = false; message.value = '논리 모델 권한이 추가되었습니다.' } catch (error) { message.value = error instanceof Error ? error.message : '서비스 권한 설정 실패' } finally { busy.value = false } }
function openPolicy() { form.value = { requestsPerMinute: quota.value?.requestsPerMinute ?? 60, monthlyTokenLimit: quota.value?.monthlyTokenLimit ?? null, mode: retention.value?.mode ?? 'METADATA_ONLY', retentionDays: retention.value?.retentionDays ?? 30, requestsPerMinuteThreshold: alert.value?.requestsPerMinuteThreshold ?? null, errorRatePercentThreshold: alert.value?.errorRatePercentThreshold ?? null, monthlyTokenUsagePercentThreshold: alert.value?.monthlyTokenUsagePercentThreshold ?? null, cooldownSeconds: alert.value?.cooldownSeconds ?? 900 }; policyOpen.value = true }
async function savePolicy() { if (!selectedId.value) return; busy.value = true; try { const limit = Number(form.value.monthlyTokenLimit); const [q, r, a] = await Promise.all([adminFetch<Quota>(`/api/admin/projects/${selectedId.value}/quota`, props.auth, { method: 'PUT', body: JSON.stringify({ requestsPerMinute: form.value.requestsPerMinute, monthlyTokenLimit: limit > 0 ? limit : null }) }), adminFetch<ContentPolicy>(`/api/admin/projects/${selectedId.value}/content-policy`, props.auth, { method: 'PUT', body: JSON.stringify({ mode: form.value.mode, retentionDays: form.value.mode === 'FULL_ENCRYPTED' ? form.value.retentionDays : null }) }), adminFetch<AlertPolicy>(`/api/admin/projects/${selectedId.value}/alert-policy`, props.auth, { method: 'PUT', body: JSON.stringify({ requestsPerMinuteThreshold: form.value.requestsPerMinuteThreshold || null, errorRatePercentThreshold: form.value.errorRatePercentThreshold || null, monthlyTokenUsagePercentThreshold: form.value.monthlyTokenUsagePercentThreshold || null, cooldownSeconds: form.value.cooldownSeconds }) })]); quota.value = q; retention.value = r; alert.value = a; policyOpen.value = false; message.value = '쿼터·경보·보관 정책이 저장되었습니다.' } catch (error) { message.value = error instanceof Error ? error.message : '정책 저장 실패' } finally { busy.value = false } }
async function revoke(key: ApiKey) { if (!confirm(`${key.name} 키를 폐기할까요?`)) return; await adminFetch(`/api/admin/api-keys/${key.id}`, props.auth, { method: 'DELETE' }); await selectProject(selectedId.value) }
async function copySecret() { await navigator.clipboard.writeText(issuedSecret.value); message.value = 'API 키를 복사했습니다.' }
watch(() => props.organizationId, () => { selectedId.value = ''; load() }); onMounted(load)
</script>

<template>
  <section class="page-stack">
    <div class="page-hero"><div><p class="eyebrow">ACCESS PLANE</p><h1>프로젝트 & API 키</h1><p>팀 소유 프로젝트별로 모델 권한, API 키, 쿼터, 알림, 보관 정책을 관리합니다.</p></div><div class="hero-actions"><button v-if="platformAdmin" class="secondary-button" @click="orgOpen = true">+ 조직</button><button class="primary-button" :disabled="!organizationId" @click="projectOpen = true">+ 프로젝트</button></div></div>
    <p v-if="message" class="inline-alert">{{ message }}</p>
    <div class="project-switcher surface-card"><div><span class="card-kicker">PROJECT SPACE</span><h2>{{ selected?.name ?? '프로젝트 선택' }}</h2><small>{{ selected?.teamId ? '팀 소유 프로젝트' : '조직 공용 프로젝트' }}</small></div><select v-model="selectedId" @change="selectProject(selectedId)"><option value="">프로젝트 선택</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.name }} · {{ project.status }}</option></select><div class="hero-actions"><button class="secondary-button" :disabled="!selectedId" @click="openPolicy">정책 설정</button><button class="secondary-button" :disabled="!selectedId" @click="serviceOpen = true">서비스 권한</button><button class="primary-button" :disabled="!selectedId" @click="keyOpen = true">API 키 발급</button></div></div>
    <div v-if="selected" class="project-policy-grid"><article class="surface-card policy-card"><span class="policy-icon">◔</span><div><span class="card-kicker">RATE & TOKEN</span><h3>{{ quota?.requestsPerMinute ?? 60 }} RPM</h3><p>{{ quota?.monthlyTokenLimit ? `${quota.monthlyTokenLimit.toLocaleString()} 월 토큰 한도` : '월 토큰 한도 없음' }}</p></div><button class="text-button" @click="openPolicy">변경</button></article><article class="surface-card policy-card"><span class="policy-icon">!</span><div><span class="card-kicker">USAGE ALERT</span><h3>{{ alert?.requestsPerMinuteThreshold ? `${alert.requestsPerMinuteThreshold} RPM 경보` : '경보 미설정' }}</h3><p>오류율·월 토큰 사용률 경보</p></div><button class="text-button" @click="openPolicy">변경</button></article><article class="surface-card policy-card"><span class="policy-icon">⌁</span><div><span class="card-kicker">CONTENT RETENTION</span><h3>{{ retention?.mode === 'FULL_ENCRYPTED' ? `암호화 원문 ${retention.retentionDays}일` : '메타데이터만' }}</h3><p>감사·소유자 역할에만 원문 열람 허용</p></div><button class="text-button" @click="openPolicy">변경</button></article></div>
    <article class="surface-card"><header class="card-header"><div><span class="card-kicker">PROJECT CREDENTIALS</span><h2>API 키</h2></div><span class="count-badge">{{ keys.length }}</span></header><div v-if="keys.length" class="data-table-wrap"><table class="data-table"><thead><tr><th>이름</th><th>Prefix</th><th>상태</th><th>마지막 사용</th><th>만료</th><th></th></tr></thead><tbody><tr v-for="key in keys" :key="key.id"><td><strong>{{ key.name }}</strong><small>{{ new Date(key.createdAt).toLocaleDateString() }} 생성</small></td><td class="mono">{{ key.keyPrefix }}••••</td><td><span class="status-chip tiny" :class="key.status === 'ACTIVE' ? 'healthy' : 'unknown'">{{ key.status }}</span></td><td>{{ key.lastUsedAt ? new Date(key.lastUsedAt).toLocaleString() : '사용 전' }}</td><td>{{ key.expiresAt ? new Date(key.expiresAt).toLocaleDateString() : '만료 없음' }}</td><td><button class="text-button danger-text" :disabled="key.status !== 'ACTIVE'" @click="revoke(key)">폐기</button></td></tr></tbody></table></div><div v-else class="empty-state"><span>⌘</span><h3>발급된 API 키가 없습니다</h3><p>키 원문은 발급 직후 한 번만 표시됩니다.</p><button class="text-button" @click="keyOpen = true">첫 API 키 발급</button></div></article>
    <BaseModal :open="orgOpen" title="새 조직" description="회사 또는 독립 운영 단위를 만듭니다." size="sm" @close="orgOpen = false"><label class="field">조직 이름<input v-model.trim="orgName" /></label><template #footer><button class="secondary-button" @click="orgOpen = false">취소</button><button class="primary-button" :disabled="busy || !orgName" @click="createOrganization">조직 생성</button></template></BaseModal>
    <BaseModal :open="projectOpen" title="새 프로젝트" description="팀을 지정하면 해당 팀의 역할 정책이 적용됩니다." size="sm" @close="projectOpen = false"><div class="modal-form"><label class="field">프로젝트 이름<input v-model.trim="projectName" placeholder="customer-support-api" /></label><label class="field">소유 팀<select v-model="projectTeamId"><option value="">조직 공용</option><option v-for="team in teams" :key="team.id" :value="team.id">{{ team.name }}</option></select></label></div><template #footer><button class="secondary-button" @click="projectOpen = false">취소</button><button class="primary-button" :disabled="busy || !projectName" @click="createProject">프로젝트 생성</button></template></BaseModal>
    <BaseModal :open="keyOpen" title="API 키 발급" description="키 원문은 한 번만 표시되며 서비스 서버의 환경 변수에 보관해야 합니다." size="sm" @close="keyOpen = false"><div class="modal-form"><label class="field">키 이름<input v-model.trim="keyName" placeholder="production-backend" /></label><label class="field">만료일 (선택)<input v-model="expiresAt" type="datetime-local" /></label></div><template #footer><button class="secondary-button" @click="keyOpen = false">취소</button><button class="primary-button" :disabled="busy || !keyName" @click="issueKey">키 발급</button></template></BaseModal>
    <BaseModal :open="serviceOpen" title="LLM 서비스 권한" description="프로젝트 API 키가 호출할 수 있는 논리 모델을 추가합니다." size="sm" @close="serviceOpen = false"><label class="field">논리 모델<select v-model="serviceId"><option value="">서비스 선택</option><option v-for="service in services.filter(item => item.enabled)" :key="service.id" :value="service.id">{{ service.serviceKey }} · {{ service.displayName }}</option></select></label><template #footer><button class="secondary-button" @click="serviceOpen = false">취소</button><button class="primary-button" :disabled="busy || !serviceId" @click="grantService">권한 부여</button></template></BaseModal>
    <BaseModal :open="policyOpen" title="프로젝트 정책" description="쿼터, 사용량 급증 알림, 암호화 보관 정책을 한 번에 설정합니다." @close="policyOpen = false"><div class="modal-form"><div class="form-grid"><label class="field">분당 요청 수<input v-model.number="form.requestsPerMinute" type="number" min="1" /></label><label class="field">월 토큰 한도<input v-model.number="form.monthlyTokenLimit" type="number" min="1" placeholder="비우면 제한 없음" /></label><label class="field">RPM 경보<input v-model.number="form.requestsPerMinuteThreshold" type="number" min="1" placeholder="미설정" /></label><label class="field">오류율 경보 (%)<input v-model.number="form.errorRatePercentThreshold" type="number" min="0.01" max="100" placeholder="미설정" /></label><label class="field">월 토큰 경보 (%)<input v-model.number="form.monthlyTokenUsagePercentThreshold" type="number" min="1" max="100" placeholder="미설정" /></label><label class="field">알림 재전송 간격 (초)<input v-model.number="form.cooldownSeconds" type="number" min="60" /></label></div><div class="retention-options"><label :class="{ active: form.mode === 'METADATA_ONLY' }"><input v-model="form.mode" type="radio" value="METADATA_ONLY" /><span><b>메타데이터만</b><small>토큰·비용·상태만 저장합니다.</small></span></label><label :class="{ active: form.mode === 'FULL_ENCRYPTED' }"><input v-model="form.mode" type="radio" value="FULL_ENCRYPTED" /><span><b>암호화된 원문</b><small>프롬프트와 응답을 AES-GCM으로 보관합니다.</small></span></label></div><label v-if="form.mode === 'FULL_ENCRYPTED'" class="field">원문 보관 일수<input v-model.number="form.retentionDays" type="number" min="1" max="365" /></label></div><template #footer><button class="secondary-button" @click="policyOpen = false">취소</button><button class="primary-button" :disabled="busy || form.requestsPerMinute < 1" @click="savePolicy">정책 저장</button></template></BaseModal>
    <BaseModal :open="secretOpen" title="API 키가 발급되었습니다" description="이 창을 닫으면 키 원문은 다시 표시되지 않습니다." @close="secretOpen = false"><div class="secret-reveal"><span>PROJECT API KEY</span><code>{{ issuedSecret }}</code><button class="secondary-button" @click="copySecret">복사</button></div><template #footer><button class="primary-button" @click="secretOpen = false">안전하게 보관했습니다</button></template></BaseModal>
  </section>
</template>
