<script setup lang="ts">
import { onMounted, ref } from 'vue'
import BaseModal from './BaseModal.vue'
type Usage = { requestCount: number; inputTokens: number; outputTokens: number; estimatedCost: number; failedRequests: number }
type Item = { requestId: string; serviceKey?: string; serviceDisplayName?: string; deploymentDisplayName?: string; stream: boolean; status: string; inputTokens?: number; outputTokens?: number; estimatedCost?: number; latencyMs?: number; failoverCount: number; startedAt: string }
const apiKey = ref(sessionStorage.getItem('aiconnect.consumerApiKey') ?? ''); const usage = ref<Usage | null>(null); const items = ref<Item[]>([]); const keyModal = ref(false); const busy = ref(false); const message = ref('프로젝트 API 키로 사용량을 조회하세요.')
async function request<T>(path: string): Promise<T> { const response = await fetch(path, { headers: { Authorization: `Bearer ${apiKey.value}` } }); if (!response.ok) throw new Error((await response.json().catch(() => ({ message: response.statusText }))).message ?? '조회 실패'); return response.json() as Promise<T> }
async function load() { if (!apiKey.value) { keyModal.value = true; return } busy.value = true; try { sessionStorage.setItem('aiconnect.consumerApiKey', apiKey.value); [usage.value, items.value] = await Promise.all([request<Usage>('/api/me/usage'), request<Item[]>('/api/me/requests')]); message.value = `최근 ${items.value.length}개 요청을 불러왔습니다.`; keyModal.value = false } catch (error) { message.value = error instanceof Error ? error.message : '사용량 조회 실패'; keyModal.value = true } finally { busy.value = false } }
function integer(value = 0) { return new Intl.NumberFormat('ko-KR').format(value) }; function cost(value = 0) { return `${new Intl.NumberFormat('ko-KR', { maximumFractionDigits: 6 }).format(value)} 원` }
onMounted(() => { if (apiKey.value) load() })
</script>
<template><section class="page-stack"><div class="page-hero"><div><p class="eyebrow">CONSUMER ANALYTICS</p><h1>사용량</h1><p>프로젝트 API 키 기준 토큰·비용·모델 사용 이력을 확인합니다.</p></div><div class="hero-actions"><button class="secondary-button" @click="keyModal = true">API 키 변경</button><button class="primary-button" :disabled="busy || !apiKey" @click="load">↻ 조회</button></div></div><p class="inline-alert">{{ message }}</p><div v-if="usage" class="metric-grid five"><article class="metric-card accent"><span>요청 수</span><strong>{{ integer(usage.requestCount) }}</strong><small>선택 기간 전체</small></article><article class="metric-card"><span>입력 토큰</span><strong>{{ integer(usage.inputTokens) }}</strong></article><article class="metric-card"><span>출력 토큰</span><strong>{{ integer(usage.outputTokens) }}</strong></article><article class="metric-card"><span>예상 비용</span><strong>{{ cost(usage.estimatedCost) }}</strong></article><article class="metric-card" :class="{ warning: usage.failedRequests > 0 }"><span>실패 요청</span><strong>{{ integer(usage.failedRequests) }}</strong></article></div><article class="surface-card"><header class="card-header"><div><span class="card-kicker">REQUEST HISTORY</span><h2>최근 요청</h2></div><span class="count-badge">{{ items.length }}</span></header><div v-if="items.length" class="data-table-wrap"><table class="data-table"><thead><tr><th>시간</th><th>논리 모델</th><th>실제 배포</th><th>상태</th><th>방식</th><th>토큰</th><th>비용</th><th>지연</th><th>Failover</th></tr></thead><tbody><tr v-for="item in items" :key="item.requestId"><td>{{ new Date(item.startedAt).toLocaleString() }}</td><td><strong>{{ item.serviceKey ?? '-' }}</strong><small>{{ item.serviceDisplayName }}</small></td><td>{{ item.deploymentDisplayName ?? '-' }}</td><td><span class="status-chip tiny" :class="item.status === 'SUCCEEDED' ? 'healthy' : 'unhealthy'">{{ item.status }}</span></td><td>{{ item.stream ? 'SSE' : 'JSON' }}</td><td>{{ integer((item.inputTokens ?? 0) + (item.outputTokens ?? 0)) }}</td><td>{{ cost(item.estimatedCost) }}</td><td>{{ integer(item.latencyMs) }} ms</td><td>{{ item.failoverCount }}</td></tr></tbody></table></div><div v-else class="empty-state"><span>◇</span><p>표시할 요청이 없습니다.</p></div></article><BaseModal :open="keyModal" title="사용량 조회 API 키" description="키는 현재 브라우저 탭의 sessionStorage에만 보관됩니다." size="sm" @close="keyModal = false"><label class="field">프로젝트 API 키<input v-model="apiKey" type="password" autocomplete="off" placeholder="sk_llmg_…" @keyup.enter="load" /></label><template #footer><button class="secondary-button" @click="keyModal = false">취소</button><button class="primary-button" :disabled="busy || !apiKey" @click="load">사용량 조회</button></template></BaseModal></section></template>
